name: Test and Lint

on: push

env:
  FIRESTORE_EMULATOR_HOST: localhost:8505
  PUBSUB_EMULATOR_HOST: localhost:8085

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      FIRESTORE_EMULATOR_HOST: localhost:8505
      PUBSUB_EMULATOR_HOST: localhost:8085
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker-compose up
        run: docker-compose up -d
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm test
  linter:
    name: Lint code
    runs-on: ubuntu-latest
    needs: test
    env:
      NODE_ENV: development
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Install deps, eslint and plugins
        run: npm i
      - name: Run linter
        run: npm run lint